### ISSUE TITLE
Questions of Training

### ISSUE THREAD

**Issue by jackydinosaur** [mwaseema/Drone-Detection#1]
Hello, thanks for the great work!!
I tried to train with NPS-Drones dataset.
'Setup environment' and 'Videos to frames and annotations to masks' is finished.
I get errors when try 'Generate image crops' .
(I had added absolute path to line 13,15,18,20 in `tools/image_crops/generate_crops_of_images_by_dividing.py`)

-------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/65848498/122665628-e3cef900-d1da-11eb-8705-c4b7cea105ba.png)
-------------------------------------------------------------------------------------------------------------------------------------------

how might able to solve it?

I am looking forward to your reply.

**Comment by mwaseema** [comment]
There can be multiple reasons for this error and every reason will be related to the availability of the data. The error type is because of the no availability of the file for the given path.
To tackle this error, you should make sure the image input folder and the ground truth input folder have the same number of files and only image files are present as non-image type files also result in None type object returned. Make sure paths to correct folders are given and for every image in the frames folder, there should be a binary mask image in the ground truth folder. If you still get this problem, try to read and check all the files using OpenCV to make sure none of the files are corrupt.

**Comment by jackydinosaur** [comment]
Thanks a lot！
I will do it.

**Comment by jackydinosaur** [comment]
Hello,
I had trained 10 epochs. 
After running 【test_model/spatial/test_and_score.py】, and obtain the result below
1.
![image](https://user-images.githubusercontent.com/65848498/123797165-7dec1b00-d918-11eb-9eb3-987048a30c58.png)
how might able to solve it?

2.
![image](https://user-images.githubusercontent.com/65848498/123797490-cdcae200-d918-11eb-83d5-5b4bff45e0e2.png)
<img width="510" alt="001" src="https://user-images.githubusercontent.com/65848498/123798101-724d2400-d919-11eb-8672-2dfc091d9ca8.png">
<img width="810" alt="002" src="https://user-images.githubusercontent.com/65848498/123799219-92311780-d91a-11eb-9fb6-ea7e1915a815.png">
<img width="806" alt="003" src="https://user-images.githubusercontent.com/65848498/123799234-98bf8f00-d91a-11eb-81f4-76c823a551a2.png">
<img width="574" alt="004" src="https://user-images.githubusercontent.com/65848498/123799254-9c531600-d91a-11eb-9b78-c480ef62da5f.png">
<img width="564" alt="005" src="https://user-images.githubusercontent.com/65848498/123799266-9f4e0680-d91a-11eb-913f-8cdea3259407.png">
Is the result correct？

I am looking forward to your reply.

**Comment by mwaseema** [comment]
Hi. Thanks for reaching out.
This problem is due to having no detections available in the prediction masks stored in the `detections` folder. There can be multiple reasons for this. One of the most obvious is a really small number of epochs, the network is currently starting to learn and more epochs would help get better results.
Also, please describe how you used the code in more detail. The flow of your data and which code files you used etc. This will help me understand your problem in more detail.

**Comment by jackydinosaur** [comment]
HI. Thanks for your reply.
 I had trained 100 epochs from the scratch.
1.setup environment
2.download NPS-Drones-Dataset. 1-40 videos for training dataset. 41-50 videos for testing dataset.
3.【tools/video_to_frames_and_masks.py】→Videos to frames and annotations to masks
![image](https://user-images.githubusercontent.com/65848498/124077327-fc140300-da79-11eb-9a8a-a6a71e7be6d0.png)

![image](https://user-images.githubusercontent.com/65848498/124077261-e6064280-da79-11eb-9375-30450b3899cf.png)

4.【tools/image_crops/generate_crops_of_images_by_dividing.py】→Generate image crops
![image](https://user-images.githubusercontent.com/65848498/124077809-3bdaea80-da7a-11eb-9014-3e7e53eae7b9.png)
![image](https://user-images.githubusercontent.com/65848498/124078470-73e22d80-da7a-11eb-8e33-e9cf11e505c0.png)

5.【train/spatial/train.py】
train/spatial/config.py
![image](https://user-images.githubusercontent.com/65848498/124078665-bd327d00-da7a-11eb-9880-4a523fc95825.png)

train result
<img width="942" alt="001" src="https://user-images.githubusercontent.com/65848498/124078848-f23ecf80-da7a-11eb-97d1-adf60899ced6.PNG">

6.`test_model/spatial/test_and_score.py`
test_model/spatial/config.py
![image](https://user-images.githubusercontent.com/65848498/124079206-7002db00-da7b-11eb-9ddd-05e58f706006.png)

test_model/spatial/checkpoint_paths.py
![image](https://user-images.githubusercontent.com/65848498/124079139-5cf00b00-da7b-11eb-9630-4188ce1ba392.png)

test result
![image](https://user-images.githubusercontent.com/65848498/124081422-1d76ee00-da7e-11eb-849c-1fa712ea36cb.png)

The output files are the same with the last message.
If more details are needed, tell me please.

**Comment by mwaseema** [comment]
Hi,

From the screenshot which you added under the **test result**, you are getting a resource exhausted error. This means the model isn't being loaded in the GPU memory due to not enough memory being allocated.
I've used GTX1080Ti for training and testing with 3 as the batch size. You'll have to figure out why you are getting this error. Some other process might be the culprit using the GPU.

Regards,

**Comment by wpfhtl** [comment]
@jackydinosaur , I have encounter some bug during 'python tools/video_to_frames_and_masks.py' as follows. It seems there's also other bugs.
Would you please help to share your version since you have succeded to compile this work? Many thanks.
ValueError: invalid literal for int() with base 10: 'time_layer:1detections:(182'

![image](https://user-images.githubusercontent.com/7974973/126885183-e8e966ee-5d09-4c8a-96bf-f16dfcaadf88.png)

**Comment by mwaseema** [comment]
Hi @wpfhtl,
The bug you are reporting here is most probably because of wrong input. Annotation files, which are available within the repository, have contents similar to the contents in the screenshot below:
![image](https://user-images.githubusercontent.com/3729172/126892634-e5615335-ab49-4282-938e-546fa9e59aaf.png)

The error is due to not being able to parse the data from files so can you please check the files you are giving as input?

Also, can you please highlight and report what other bugs you've found so I can have a look?

Thanks,

**Comment by wpfhtl** [comment]
@mwaseema , thanks for your comment, I found my error is because I used the original "Video_Annotation" in the NPS dataset (https://engineering.purdue.edu/~bouman/UAV_Dataset/). But I found there's inconsistency between the file from the original "Video_Annotation" and your folder "annotations"
![image](https://user-images.githubusercontent.com/7974973/126894361-582dd5ce-1f0e-4e42-bd15-0e03a5b843e9.png)
![image](https://user-images.githubusercontent.com/7974973/126894373-055e5e2f-1932-474d-87ac-f1254f0df152.png)

**Comment by wpfhtl** [comment]
@mwaseema  the test result of spatial model is all zero for all the images. Do you have any idea about what's the reason? The model is trained with 100 epochs
![image](https://user-images.githubusercontent.com/7974973/127163862-b802e4ec-53b6-4f7e-9f04-b4a3520c3ff1.png)

**Comment by mwaseema** [comment]
> @mwaseema , thanks for your comment, I found my error is because I used the original "Video_Annotation" in the NPS dataset (https://engineering.purdue.edu/~bouman/UAV_Dataset/). But I found there's inconsistency between the file from the original "Video_Annotation" and your folder "annotations"

We've re-annotated every frame to make annotations well localized and have exported our annotations in a different format.

> @mwaseema the test result of spatial model is all zero for all the images. Do you have any idea about what's the reason? The model is trained with 100 epochs

There can be lots of reasons for this, can you please describe each step how you did what? What configurations did you use? If possible, can you please attach screenshots or output of the scripts that'll help me understand and tell you what was the problem and how you can fix it.

Regards,
