### ISSUE TITLE
Confusion about the quantitative results of the NPS dataset

### ISSUE THREAD

**Issue by mouyihan** [mwaseema/Drone-Detection#14]
Why maskrcnn achieved the same AP as Dogfight with a lower precision. look forward to your help.

**Comment by mwaseema** [comment]
Hi @mouyihan,

Thanks for your question.

As you can see from the scores, MaskRCNN has good number of true positives indicated by recall. False positives are responsible for low precision and as a result precision moved up and down (zigzag movement of precision).

While calculating average precision, we use interpolation and calculate the area under the curve. We are using (standard) all point interpolation (https://github.com/mwaseema/Drone-Detection/issues/13#issuecomment-1366042109), most of those lower precision points didn't affect the overall AP due to interpolation.

I hope this answers your question.

Regards,
Waseem
